spring:
  application:
    name: jhips_test
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      ddl-auto: create
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      thread-name-prefix: jhips-test-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: jhips-test-scheduling-
      pool:
        size: 2
  thymeleaf:
    mode: HTML
  output:
    ansi:
      console-available: true

  jackson:
    serialization:
      indent-output: true
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:h2:mem:jhips_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: jhips_test
      password:
      hikari:
        poolName: Hikari
        auto-commit: false
    h2:
      console:
        enabled: false
    jpa:
      #    database-platform: io.github.jhipster.domain.util.FixedH2Dialect
      show-sql: true
      properties:
        hibernate.id.new_generator_mappings: true
        hibernate.connection.provider_disables_autocommit: true
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false

    thymeleaf:
      cache: false

server:
  servlet:
    session:
      cookie:
        http-only: true


logging:
  level:
    ROOT: INFO
#    io.github.jhipster: DEBUG
    com.shafaat.jhips: INFO

clientApp:
  name: jhips